# ===================================================================
# GENERAL PROPERTIES
# ===================================================================
server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
      format_sql: true
      database-platform: org.hibernate.dialect.Oracle12cDialect
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XE
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  web:
    resources:
      static-locations: classpath:/static/

# ===================================================================
# SECURITY PROPERTIES
# ===================================================================
security:
  jwt:
    key: 08af2447a30c9c090b3595e6b45cead32eb587dcb1892aae31f073dcb31bce95
    lifeTime: 631138000000
    user:
      generator: Pizarras-Elenita